defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.93
  decay_steps: 14650
optimizer:
  lr: 0.01
training:
  rec_results_freq : 2000
  rec_constraint_freq: 1000
  rec_monitor_freq: 100
  max_steps : 2500000

